// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx06k9YPpMlYA4qLYUrHZaDJ_E0WB_WOM',
    appId: '1:134942953873:web:ad5472a0d89ce09e54ca30',
    messagingSenderId: '134942953873',
    projectId: 'aktuel-urunler-e74b5',
    authDomain: 'aktuel-urunler-e74b5.firebaseapp.com',
    storageBucket: 'aktuel-urunler-e74b5.appspot.com',
    measurementId: 'G-T2QL9J425D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxVABYVljFxlkSb-zfneVDZ_bDGUI8QGs',
    appId: '1:134942953873:android:3b60f30b517cefc754ca30',
    messagingSenderId: '134942953873',
    projectId: 'aktuel-urunler-e74b5',
    storageBucket: 'aktuel-urunler-e74b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA20tDQtV_LW9TokCaUyWnTjk3pWxryX4Y',
    appId: '1:134942953873:ios:c2b442687cd277a954ca30',
    messagingSenderId: '134942953873',
    projectId: 'aktuel-urunler-e74b5',
    storageBucket: 'aktuel-urunler-e74b5.appspot.com',
    iosClientId: '134942953873-ov77c1p9bg10sgln0nlvv5j1ohhflh8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aktuelUrunlerBimA101Sok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA20tDQtV_LW9TokCaUyWnTjk3pWxryX4Y',
    appId: '1:134942953873:ios:c2b442687cd277a954ca30',
    messagingSenderId: '134942953873',
    projectId: 'aktuel-urunler-e74b5',
    storageBucket: 'aktuel-urunler-e74b5.appspot.com',
    iosClientId: '134942953873-ov77c1p9bg10sgln0nlvv5j1ohhflh8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aktuelUrunlerBimA101Sok',
  );
}
