// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8svPwV_08y-apSFApO81MWsW0YhlDSw',
    appId: '1:94148954337:web:743bd6a64321c838180fa0',
    messagingSenderId: '94148954337',
    projectId: 'aktuelurunler-31dc9',
    authDomain: 'aktuelurunler-31dc9.firebaseapp.com',
    storageBucket: 'aktuelurunler-31dc9.appspot.com',
    measurementId: 'G-8TRC1RCCLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBnnV65TDssvQYI_bx9-3vBenY9wzMn8',
    appId: '1:94148954337:android:4116f8c367c6c250180fa0',
    messagingSenderId: '94148954337',
    projectId: 'aktuelurunler-31dc9',
    storageBucket: 'aktuelurunler-31dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-uUM0IAR3x8w1KHna8nnC_5AZad2E28',
    appId: '1:94148954337:ios:39f8eb5da35d7430180fa0',
    messagingSenderId: '94148954337',
    projectId: 'aktuelurunler-31dc9',
    storageBucket: 'aktuelurunler-31dc9.appspot.com',
    androidClientId: '94148954337-uuljngsjv4i12m1b9uhchni8t6i90i7o.apps.googleusercontent.com',
    iosClientId: '94148954337-pbch64lcre7iq5nqnp0ksvf1eo4tqip1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aktuelUrunlerBimA101Sok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-uUM0IAR3x8w1KHna8nnC_5AZad2E28',
    appId: '1:94148954337:ios:39f8eb5da35d7430180fa0',
    messagingSenderId: '94148954337',
    projectId: 'aktuelurunler-31dc9',
    storageBucket: 'aktuelurunler-31dc9.appspot.com',
    androidClientId: '94148954337-uuljngsjv4i12m1b9uhchni8t6i90i7o.apps.googleusercontent.com',
    iosClientId: '94148954337-pbch64lcre7iq5nqnp0ksvf1eo4tqip1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aktuelUrunlerBimA101Sok',
  );
}
